// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMbPoPV_VmBQ4n7DajxBxorNgcnOPtz0',
    appId: '1:89860089693:web:ce7110036e78a7dbdd2ab4',
    messagingSenderId: '89860089693',
    projectId: 'your-project-name-b1e6c',
    authDomain: 'your-project-name-b1e6c.firebaseapp.com',
    databaseURL: 'https://your-project-name-b1e6c-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-name-b1e6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDE9ZYJNYunC0GOg8CwVYAoYviFZPKzg',
    appId: '1:89860089693:android:d46d8634ecad7f92dd2ab4',
    messagingSenderId: '89860089693',
    projectId: 'your-project-name-b1e6c',
    databaseURL: 'https://your-project-name-b1e6c-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-name-b1e6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5n7xBCS4HAV_gM3pgxDlsqV2jIxgllw',
    appId: '1:89860089693:ios:3e93770763cdc4d1dd2ab4',
    messagingSenderId: '89860089693',
    projectId: 'your-project-name-b1e6c',
    databaseURL: 'https://your-project-name-b1e6c-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-name-b1e6c.appspot.com',
    iosClientId: '89860089693-89gb7q1dbb7ek8kq4kuv9081jje4jsgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5n7xBCS4HAV_gM3pgxDlsqV2jIxgllw',
    appId: '1:89860089693:ios:e1e50610be494146dd2ab4',
    messagingSenderId: '89860089693',
    projectId: 'your-project-name-b1e6c',
    databaseURL: 'https://your-project-name-b1e6c-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-name-b1e6c.appspot.com',
    iosClientId: '89860089693-35peo2bi7v4ikth48cc8vtg84p3i13ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgpt.RunnerTests',
  );
}
