// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


///
///
///

// 
// *** Delete my firebase_options.dart file here because you are gonna have your own firebase_option.dart ***
// *** file when you done setup flutterfire ***



///
///
///


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0bSSvpOFAL1YuUwTsK3vDYjV27C7LR_0',
    appId: '1:145097866406:web:3175d933a421c9c08a8867',
    messagingSenderId: '145097866406',
    projectId: 'brycen-chat-app',
    authDomain: 'brycen-chat-app.firebaseapp.com',
    databaseURL: 'https://brycen-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'brycen-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67wWct_m4pyVWRpntRKnForjg7AoafDA',
    appId: '1:145097866406:android:3b12ca832e30c2568a8867',
    messagingSenderId: '145097866406',
    projectId: 'brycen-chat-app',
    databaseURL: 'https://brycen-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'brycen-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWsPcC_V4wsl0T-hTA4M9xuiV0EBo6mig',
    appId: '1:145097866406:ios:8171dc96945181618a8867',
    messagingSenderId: '145097866406',
    projectId: 'brycen-chat-app',
    databaseURL: 'https://brycen-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'brycen-chat-app.appspot.com',
    iosClientId: '145097866406-rqva7iail5dgd33fmrque0rlfi3m1v0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWsPcC_V4wsl0T-hTA4M9xuiV0EBo6mig',
    appId: '1:145097866406:ios:bc01fd59b7525ef38a8867',
    messagingSenderId: '145097866406',
    projectId: 'brycen-chat-app',
    databaseURL: 'https://brycen-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'brycen-chat-app.appspot.com',
    iosClientId: '145097866406-tk28hldndd3m1b7gdli5okb67cgsvqfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgpt.RunnerTests',
  );
}
